name: PillarsPlugin
version: 1.0
main: org.example.pillars.PillarsPlugin
api-version: 1.21
commands:
  pillars:
    description: Pillars main command
    usage: /<command> <join|leave|forcestart>
    aliases: [p]