name: PillarsPlugin
version: 1.0
main: org.example.pillars.PillarsPlugin
api-version: 1.21
softdepend: [PlaceholderAPI, TAB]
commands:
  pillars:
    description: main game command
    usage: /<command>
    aliases: [p]
permissions:
  pillars.forcestart:
    description: allows force starting games
    default: op
  pillars.admin:
    description: allows editing gameplay configuration in-game
    default: op
