name: PillarsPlugin
version: 1.0
main: org.example.pillars.PillarsPlugin
api-version: 1.21
softdepend: [PlaceholderAPI, TAB]
commands:
  pillars:
    description: основная игровая команда
    usage: /<command>
    aliases: [p]
permissions:
  pillars.forcestart:
    description: разрешает принудительно запускать игры
    default: op
  pillars.admin:
    description: разрешает изменять игровые настройки
    default: op
